#!/bin/bash
  
function man_page ()
  { # Begin man page
  cat<< EOF
  NAME
       acctpasswd by Clen
  SYNOPSYS
       acctpasswd [options] USERNAME
  DESCRIPTION
       
  OPTIONS
       -a CPANEL_USERNAME
            Add restrictions to specified USERNAME
       -r CPANEL_USERNAME
            Remove restrictions from specified USERNAME
       -c CPANEL_USERNAME
            Check for restrictions in place for USERNAME
       -h
            Displays this man page.
  Exiting.

  
EOF
} # End man page


while getopts ":a:r:c:h*" opt; do
  case $opt in
    h) # Begin man page
      man_page
      exit 0
    ;; # End man page
    *) # Begin incorrect input catch all
      catchall_run="1"
      error_check
      man_page
      exit 0
    ;; # End incorrect input catch all
  esac
done
# End main


https://docs.influxdata.com/influxdb/v1.5/tools/shell/
https://docs.influxdata.com/influxdb/v1.5/tools/web_admin/
https://docs.influxdata.com/influxdb/v1.5/about_the_project/releasenotes-changelog/
https://docs.influxdata.com/influxdb/v1.5/introduction/installation/
https://www.itsadc.com/super-simple-simon-grafana-setup-part-1-basic-setup/
http://docs.grafana.org/guides/basic_concepts/
http://docs.grafana.org/installation/configuration/
https://www.linuxtechi.com/install-zabbix-3-0-on-centos-7-rhel-7/
https://www.howtoforge.com/tutorial/install-zabbix-monitoring-server-and-agent-on-debian-9/
http://docs.grafana.org/installation/debian/#database
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777654
https://eapyl.github.io/article/InfluxDB-cant-be-started-as-a-service-21-December-2016.html
https://jansipke.nl/monitoring-hosts-with-collectd-influxdb-and-grafana/
https://sweetcode.io/getting-started-grafana-influxdb/
https://wiki.opnfv.org/display/fastpath/Installing+and+configuring+InfluxDB+and+Grafana+to+display+metrics+with+collectd#space-menu-link-content
https://www.influxdata.com/blog/how-to-use-grafana-with-influxdb-to-monitor-time-series-data/
http://docs.grafana.org/features/datasources/influxdb/
